# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

strategy:
  matrix:
  #  linux:
 #     imageName: 'ubuntu-16.04'
  #  mac:
   #   imageName: 'macos-10.13'
    windows:
      imageName: 'vs2017-windows-2019'

pool:
  vmImage: $(imageName)

steps:
- task: run-vcpkg@0
  inputs:
    cleanAfterBuild: false

- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install emsdk'

- script: |
    cd ..
    git init
    git clone https://github.com/emscripten-core/emsdk.git
    ./emsdk/emsdk install latest
    ./emsdk/emsdk activate latest
    ./emsdk/emsdk_env.ps1
    npm install
    npm run test
  displayName: 'npm install and build'

- task: CmdLine@2
  inputs:
    script: |
      dir
      git status
      cd ..
      git status
  displayName: 'status'
- script: 
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
